version: '3.8'

services:
  laravel:
    image: php:8.2-fpm
    container_name: laravel-app
    volumes:
      - ./app:/var/www/html
      - ./entrypoint.sh:/entrypoint.sh
    networks:
      - laravel-net
    ports:
      - "8000:80"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=laravel_password
    entrypoint: /entrypoint.sh

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-net
    ports:
      - "3306:3306"

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    ports:
      - "8080:80"
    networks:
      - laravel-net

volumes:
  mysql_data:

networks:
  laravel-net:

